import os
USERNAME = os.getenv("SIMO_USERNAME", "simo-busanhcm")
PASSWORD = os.getenv("SIMO_PASSWORD", "simo660")
CONSUMER_KEY = os.getenv("SIMO_CONSUMER_KEY", "V2sF9dfIfbqXAkBfyauNz9WTJQoa")
CONSUMER_SECRET = os.getenv("SIMO_CONSUMER_SECRET", "lnr90QpFPfClcm1chY5wijrLH08a")
TOKEN_URL = os.getenv("SIMO_TOKEN_URL", "https://mgsimotest.sbv.gov.vn/token")
ENTRYPOINT_URL_001 = os.getenv("SIMO_ENTRYPOINT_URL_001", "https://mgsimotest.sbv.gov.vn/simo/khdn/1.0/upload-bao-cao-danh-sach-tktt-khdn-api")
ENTRYPOINT_URL_002 = os.getenv("SIMO_ENTRYPOINT_URL_002", "https://mgsimotest.sbv.gov.vn/simo/khdn/1.0/upload-bao-cao-danh-sach-tktt-khdn-nngl-api")
ENTRYPOINT_URL_003 = os.getenv("SIMO_ENTRYPOINT_URL_003", "https://mgsimotest.sbv.gov.vn/simo/khdn/1.0/upload-bao-cao-cap-nhat-tktt-khdn-nngl-api")
ENTRYPOINT_URL_004 = os.getenv("SIMO_ENTRYPOINT_URL_004", "https://mgsimotest.sbv.gov.vn/simo/khdn/1.0/upload-bao-cao-cap-nhat-danh-sach-tktt-khdn-api")
